# Generated by Django 4.2.30 on 2026-07-29 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_product_created_at_alter_product_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_src',
            field=models.CharField(default='', max_length=350),
        ),
    ]
