# Generated by Django 4.2.30 on 2026-08-01 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_image_src'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Brand',
            new_name='ProductCategory',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.productcategory'),
        ),
    ]
