# Generated by Django 4.2.30 on 2026-08-01 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_rename_brand_productcategory_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productcategory',
            old_name='slug',
            new_name='url_name',
        ),
    ]
