# Generated by Django 4.2.30 on 2026-08-04 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_rename_slug_productcategory_url_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcategory',
            name='name',
        ),
        migrations.RemoveField(
            model_name='productcategory',
            name='url_name',
        ),
        migrations.AddField(
            model_name='productcategory',
            name='title',
            field=models.CharField(default='', max_length=100, verbose_name='عنوان'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='url_title',
            field=models.SlugField(default='', unique=True, verbose_name='عنوان در url'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.productcategory', verbose_name='دسته بندی'),
        ),
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(max_length=50, verbose_name='کد محصول'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_src',
            field=models.CharField(default='', max_length=350, verbose_name='آدرس عکس'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200, verbose_name='نام محصول'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.PositiveIntegerField(verbose_name='قیمت'),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(default='', verbose_name='موجودی'),
        ),
    ]
