# Generated by Django 4.2.30 on 2026-08-07 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_productcategory_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='url_title',
            field=models.SlugField(default='', verbose_name='عنوان در url'),
        ),
    ]
