# Generated by Django 4.2.30 on 2026-08-07 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_module', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactsUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('full_name', models.CharField(max_length=200, verbose_name='نام و نام خانوادگی')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('message', models.TextField(max_length=350, verbose_name='متن پیام')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('response', models.TextField(max_length=350, verbose_name='پاسخ ادمین')),
                ('is_read_by_admin', models.BooleanField(default=False, verbose_name='خوانده شده/نشده')),
            ],
        ),
        migrations.DeleteModel(
            name='ContactUs',
        ),
    ]
