# Generated by Django 4.2.30 on 2026-08-09 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_module', '0002_contactsus_delete_contactus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactsus',
            options={'verbose_name': 'تماس با ما', 'verbose_name_plural': 'لیست تماس با ما'},
        ),
    ]
